/**
 * BudgetProfi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IncomeDto } from '../../../../../../../../Desktop/model/incomeDto';
import { OutcomeDto } from '../../../../../../../../Desktop/model/outcomeDto';

/**
 * План
 */
export interface PlanDto {
    id: string;
    startDate: string;
    endDate: string;
    initialBalance: number;
    currentBalance: number;
    currentDailyBalance: number;
    incomes: Array<IncomeDto>;
    outcomes: Array<OutcomeDto>;
}
